import test from 'node:test';
import assert from 'node:assert/strict';
import { newProject, makeBlock, recommendSpan, autoBlocks, slideCount, moveBlock, joinNext, splitBlock, validateProject, RATIOS, MAX_SLIDES, effectiveAssetSize, neutralPreprocess } from '../src/model.js';
const asset = (id, width=2400, height=1600) => ({id,name:`${id}.jpg`,width,height});
function sample() { const assets=[asset('a'),asset('b',1200,1800),asset('c')]; return {assets,project:{...newProject(),blocks:autoBlocks(assets,'4:5')}}; }

test('default is a valid empty, portrait, JPEG project',()=>{const p=newProject(); assert.equal(p.ratio,'4:5');assert.equal(p.format,'jpeg');assert.equal(slideCount(p),0); assert.ok(validateProject(p,[]));});
test('all output widths are 1080 with integer heights',()=>{assert.deepEqual(RATIOS,{'4:5':{width:1080,height:1350},'3:4':{width:1080,height:1440},'1:1':{width:1080,height:1080}});});
for(const [w,h,ratio,expected] of [[2400,1600,'4:5',2],[2400,1600,'3:4',2],[1200,1800,'4:5',1],[1000,1000,'1:1',1],[4096,300,'4:5',6],[3600,1200,'1:1',3]]) test(`span suggestion ${w}×${h} ${ratio} → ${expected}`,()=>assert.equal(recommendSpan(asset('x',w,h),ratio),expected));
test('20 landscape photos fit into 20 slides without dropping/reordering any',()=>{const photos=Array.from({length:20},(_,i)=>asset(`p${i}`));const blocks=autoBlocks(photos,'4:5');assert.equal(blocks.reduce((n,b)=>n+b.span,0),20);assert.deepEqual(blocks.flatMap(b=>b.photoIds),photos.map(a=>a.id));});
test('budget pressure reduces the largest spans first',()=>{const blocks=autoBlocks([asset('wide',4096,512),asset('portrait',900,1200)],'4:5',4); assert.deepEqual(blocks.map(b=>b.span),[3,1]);});
test('auto layout rejects more photos than its budget',()=>assert.throws(()=>autoBlocks([asset('a'),asset('b')],'4:5',1)));
test('move is immutable and boundaries are no-ops',()=>{const {project}=sample();const before=structuredClone(project);const moved=moveBlock(project,0,1);assert.deepEqual(project,before);assert.equal(moved.blocks[1].photoIds[0],'a');assert.equal(moveBlock(project,0,-1),project);assert.equal(moveBlock(project,2,1),project);});
test('join then split preserves photo order and valid references',()=>{const {assets,project}=sample();const joined=joinNext(project,0);assert.deepEqual(joined.blocks[0].photoIds,['a','b']);assert.equal(joined.blocks[0].layout,'overlap');assert.ok(validateProject(joined,assets));const split=splitBlock(joined,0);assert.deepEqual(split.blocks.flatMap(b=>b.photoIds),['a','b','c']);assert.ok(validateProject(split,assets));});
test('joining the last block or a pair is a no-op',()=>{const {project}=sample();assert.equal(joinNext(project,2),project);const joined=joinNext(project,0);assert.equal(joinNext(joined,0),joined);});
test('splitting refuses to exceed slide budget',()=>{const photos=Array.from({length:20},(_,i)=>asset(`p${i}`,900,1200));let p={...newProject(),blocks:autoBlocks(photos,'4:5')};p=joinNext(p,0);p.blocks[0].span=1;p.blocks[1].span=2;assert.equal(slideCount(p),20);assert.throws(()=>splitBlock(p,0));});
for(const [name,mutate] of [
 ['unknown version',p=>p.version=9],['bad id',p=>p.id='<script>'],['oversized title',p=>p.title='x'.repeat(101)],['unknown ratio',p=>p.ratio='constructor'],['unknown theme',p=>p.theme='prototype'],['unknown format',p=>p.format='svg'],['fractional span',p=>p.blocks[0].span=1.5],['too many splits',p=>p.blocks[0].span=7],['missing photo',p=>p.blocks[0].photoIds=['absent']],['duplicate photo',p=>p.blocks[1].photoIds=['a']],['wrong pair',p=>p.blocks[0].layout='duo'],['invalid fit',p=>p.blocks[0].fit='squeeze'],['unsafe focus',p=>p.blocks[0].transforms.a.focusX=Infinity],['excess zoom',p=>p.blocks[0].transforms.a.zoom=4],['duplicate block id',p=>p.blocks[1].id=p.blocks[0].id]
]) test(`untrusted project rejected: ${name}`,()=>{const {project,assets}=sample();mutate(project);assert.throws(()=>validateProject(project,assets));});
test('asset dimensions must be limited integers',()=>{const {project,assets}=sample();assets[0].width=50000;assert.throws(()=>validateProject(project,assets));});
test('rotation and crop produce effective dimensions without changing source dimensions',()=>{const a=asset('a',2400,1600);a.preprocess={...neutralPreprocess(),rotation:90,crop:{left:.1,right:.1,top:0,bottom:0}};assert.deepEqual(effectiveAssetSize(a),{width:1280,height:2400,rotatedWidth:1600.0000000000002,rotatedHeight:2400});assert.deepEqual([a.width,a.height],[2400,1600]);});
test('square preprocessing changes a landscape recommendation from two pages to one',()=>{const a=asset('a',2400,1600);a.preprocess={rotation:0,crop:{left:1/6,right:1/6,top:0,bottom:0}};assert.deepEqual(effectiveAssetSize(a).width,effectiveAssetSize(a).height);assert.equal(recommendSpan(a,'4:5'),1);});
test('untrusted preprocessing crop is rejected',()=>{const {project,assets}=sample();assets[0].preprocess={rotation:0,crop:{left:.6,right:.4,top:0,bottom:0}};assert.throws(()=>validateProject(project,assets),/前処理/);});
test('all admitted photo counts and ratios obey the invariants',()=>{for(let n=0;n<=20;n++)for(const ratio of Object.keys(RATIOS)){const assets=Array.from({length:n},(_,i)=>asset(`p${i}`,900+i*137,600+(i%3)*470));const project={...newProject(),ratio,blocks:autoBlocks(assets,ratio)};assert.ok(slideCount(project)<=MAX_SLIDES);assert.ok(validateProject(project,assets));}});
